[General]
key_pmi=3328402813
key_pmi_invite_msg="Deven Tseng is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Deven Tseng's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://zoom.us/j/3328402813?pwd=aXBGbFg3TDVSd3psTXd1Wmw0bDhqdz09\r\n\r\nMeeting ID: 332 840 2813\r\nPasscode: EXG35K\r\n\r\n"
