[General]
GeoLocale=system
PhoneLiveTrans_Window_Mode_ayoi2d9uq1gkaf3nmhtagq=0
PhoneLiveTrans_Window_Mode_jszm9rnrqikvrbka95id-w=0
SensitiveInfoMaskOn=true
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
blockUntrustedSSLCert=false
captureHDCamera=true
chatListPanelLastWidth=230
conf.webserver=https://zoom.us
conf.webserver.vendor.default=https://us04web.zoom.us
currentMeetingId=94912157589
deviceID=C8:94:02:A9:DD:CF
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCloudSwitch=false
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableWaylandShare=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
host.auto.grab.interval=10
isTransCoding=false
logLevel=info
newMeetingWithVideo=true
playSoundForNewMessage=false
scaleFactor=1
shareBarTopMargin=0
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
timeFormat12HoursEnable=true
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=

[AS]
showframewindow=true

[CodeSnippet]
lastCodeType=0
wrapMode=0

[chat.recent]
recentlast.session=

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="712,680"
main_frame_pixel_pos_wide="1328,680"
