local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Find files" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = "Live grep" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Find buffers" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = "Help" })
vim.keymap.set('n', '<leader>lr', builtin.lsp_references, {desc = "Find references"})
vim.keymap.set('n', '<leader>ls', builtin.lsp_document_symbols, {desc = "Find functions"})
vim.keymap.set('n', '<leader>ld', builtin.diagnostics, {desc = "Find errors"})
